export { default as CheckAuth } from "./CheckAuth"
export { default as Home } from "./Home"
export { default as Login } from "./Login"
export { default as NotFound } from "./NotFound"
export { default as Page } from "./Page"
